package com.teamspace.teamspace.notification.enums;

public enum NotificationType {
    TASK_ASSIGNED,
    TASK_COMMENT,
    FILE_UPLOADED,
    MEETING_CREATED,
    TASK_REVIEW_SUBMITTED,
    TASK_REVIEW_APPROVED,
    TASK_REVIEW_CHANGES_REQUESTED
    ,TASK_UNASSIGNED
    ,TASK_MENTION
    ,TASK_WATCHED_COMMENT
    ,TASK_DUE_SOON
    ,TASK_OVERDUE
    ,WEEKLY_PLAN_STARTED
    ,WEEKLY_PLAN_ENDING
    ,WEEKLY_PLAN_COMPLETED
    ,WEEKLY_PLAN_CANCELLED
}
