package com.teamspace.teamspace.taskactivity.service;
import java.util.*; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import com.teamspace.teamspace.exception.*; import com.teamspace.teamspace.task.entity.Task; import com.teamspace.teamspace.task.repository.TaskRepository; import com.teamspace.teamspace.task.repository.TaskReviewHistoryRepository; import com.teamspace.teamspace.taskactivity.dto.*; import com.teamspace.teamspace.taskactivity.entity.TaskActivity; import com.teamspace.teamspace.taskactivity.repository.TaskActivityRepository; import com.teamspace.teamspace.user.entity.User; import com.teamspace.teamspace.user.repository.UserRepository; import com.teamspace.teamspace.workspace.dto.WorkspaceUserSummary; import com.teamspace.teamspace.workspace.repository.WorkspaceMemberRepository; import lombok.RequiredArgsConstructor;
@Service @RequiredArgsConstructor
public class TaskActivityService {
 private final TaskActivityRepository repository; private final TaskReviewHistoryRepository reviewRepository; private final TaskRepository taskRepository; private final UserRepository userRepository; private final WorkspaceMemberRepository memberRepository;
 @Transactional public void log(Task task,User actor,String action,String field,String oldValue,String newValue,String description){repository.save(TaskActivity.builder().task(task).actor(actor).actionType(action).fieldName(field).oldValue(oldValue).newValue(newValue).metadata(description).build());}
 @Transactional(readOnly=true) public TaskTimelinePage timeline(Long taskId,int page,int size,Authentication auth){Task task=taskRepository.findById(taskId).orElseThrow(()->new ResourceNotFoundException("Khong tim thay task"));User u=user(auth);if(!memberRepository.existsByWorkspaceIdAndUserId(task.getProject().getWorkspace().getId(),u.getId()))throw new ForbiddenException("Ban khong thuoc du an");List<TaskTimelineEntry> entries=new ArrayList<>();repository.findByTaskId(taskId,org.springframework.data.domain.Pageable.unpaged()).forEach(a->entries.add(TaskTimelineEntry.builder().id(a.getId()).source("ACTIVITY").actionType(a.getActionType()).fieldName(a.getFieldName()).oldValue(a.getOldValue()).newValue(a.getNewValue()).description(a.getMetadata()).actor(a.getActor()==null?null:WorkspaceUserSummary.from(a.getActor())).createdAt(a.getCreatedAt()).build()));reviewRepository.findByTaskIdOrderByCreatedAtAscIdAsc(taskId).forEach(r->entries.add(TaskTimelineEntry.builder().id(r.getId()).source("REVIEW").actionType(r.getAction().name()).description(r.getComment()).actor(r.getActor()==null?null:WorkspaceUserSummary.from(r.getActor())).createdAt(r.getCreatedAt()).build()));entries.sort(Comparator.comparing(TaskTimelineEntry::getCreatedAt).reversed());int safeSize=Math.max(1,Math.min(size,100)),from=Math.min(Math.max(0,page)*safeSize,entries.size()),to=Math.min(from+safeSize,entries.size());return TaskTimelinePage.builder().content(entries.subList(from,to)).page(Math.max(0,page)).size(safeSize).totalElements(entries.size()).totalPages((int)Math.ceil(entries.size()/(double)safeSize)).build();}
 private User user(Authentication a){if(a==null||a.getName()==null)throw new UnauthorizedException("Ban chua dang nhap");return userRepository.findByEmail(a.getName()).orElseThrow(()->new UnauthorizedException("Khong tim thay user"));}
}
